variable "aws_region" {
  type    = string
  default = "ap-south-1"
}

variable "aws_profile" {
  type    = string
  default = "rds-LLM" # read-only; apply requires an admin profile, deliberately not defaulted
}

# --- Real identifiers. Values come from terraform.tfvars, generated by
# --- ./generate-tfvars.sh from the private mapping (never committed).

variable "instance_id" { type = string }
variable "eip_allocation_id" { type = string }
variable "eip_association_id" { type = string }
variable "sg_main_id" { type = string }
variable "subnet_id" { type = string }
variable "vpc_id" { type = string }
variable "key_pair_name" { type = string }
variable "instance_profile_name" {
  type    = string
  default = "{{IAM_ROLE_BACKUP}}"
}

variable "volume_ids" {
  type        = map(string)
  description = "root, todo_prod, skilltree_prod, tinysite_prod, skilltree_stg, staging_shared"
}

variable "dlm_policy_ids" {
  type        = map(string)
  description = "default, tinysite, skilltree"
}

variable "backup_buckets" {
  type        = map(string)
  description = "skilltree, tinysite"
}
